<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
	public function getAdvertWithCategories(array $categoryNames){
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.categories', 'c')->addSelect('c');

        $qb->where($qb->expr()->in('c.name', $categoryNames));

        return $qb->getQuery()->getResult();
    }

    public function getLastNAdverts($n){
    	$qb = $this->createQueryBuilder('ad');

    	$qb->orderBy('ad.date', 'DESC')->setMaxResults($n);

    	return $qb->getQuery()->getResult();
    }
}
